### ISSUE TITLE
`public_key` name collision in DeviceConfigBuilder and PeerConfigBuilder

### ISSUE THREAD

**Issue by jamilbk** [firezone/wireguardex#25]
```
== Compilation error in file lib/meshed/peer.ex ==
** (CompileError) lib/meshed/peer.ex:85: function public_key/2 imported from both Wireguardex.PeerConfigBuilder and Wireguardex.DeviceConfigBuilder, call is ambiguous
    (elixir 1.13.4) expanding macro: Kernel.|>/2
    lib/meshed/peer.ex:87: Meshed.Peer.peer_to_config/1
```

Is `public_key` needed in `DeviceConfigBuilder`? Is there a situation where someone would want to set the public key on the interface?

**Comment by akrousset** [comment]
I was exposing the same configuration fields present for wireguard-control's `DeviceBuilder` in Rust. It more than likely isn't needed, because the public key will be generated for us when only setting  `private_key`.

**Comment by jamilbk** [comment]
Ah I see. In that case we can leave it in 👍🏼
